substitutions:
  device_name: grgdo
  device_comment: Garage Door Controller
  device_type: ESP32-C6-H4 WiFi6 BT5 IEEE802.15.4 Single Core + LP Core 160MHz
  disp_name: GRGDOv3
  id_prefix: grgdov3
  friendly_name: "GRGDOv3"
  branch: master
  uart_tx_pin: GPIO5            # J4 Pin 1 or 3 Red CTRL
  uart_rx_pin: GPIO4            # J4 Pin 1 or 3 Red CTRL
  input_obst_pin: None #GPIO20        # J4 Pin 4 Grey OBST - not required with secplus_gdo
  dry_contact_open_pin: GPIO21  # J4 Pin 6 Green
  dry_contact_close_pin: GPIO22 # J4 Pin 7 Blue
  dry_contact_light_pin: GPIO23 # J4 Pin 8 Orange
  tof_sda_pin: GPIO11           # GPIO11 = v3, GPIO26 = v2 board, GPIO3 = v1 board
  tof_scl_pin: GPIO10           # GPIO10 = v3, GPIO25 = v2 board, GPIO1 = v1 board
  dht22_pin: GPIO19             # AUX1:GPIO10, AUX2:GPIO19 = v3, AUX1:GPIO26 = v2, AUX1:GPIO3 = v1 board
  status_pin: GPIO6
  garage_door_cover_name: Garage Door
  garage_light_name: Garage Light
  garage_openings_name: Garage Openings
  garage_lock_name: Lock
  garage_motion_name: Motion
  garage_obstruction_name: Obstruction
  garage_motor_name: Motor
  garage_button_name: Wall Button
  garage_sync_name: Synced

esphome:
  name: ${device_name}
  friendly_name: ${disp_name}
  name_add_mac_suffix: true
  project:
    name: "Gelidus Research.Garage Door Controller"
    version: "1.0.0"
  on_boot:
    - priority: -100
      then:
        lambda: id(${id_prefix}).start_gdo();

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf

# This board configuration enables the correct pins for the ESP32-C6.
# The v3 board has different pin assignments for the AUX ports
# AUX1 (4Pin): GPIO11 and GPIO12, AUX2 (3Pin): GPIO19
# The ToF and DHT22 sensors are connected to the AUX1 and AUX2 ports respectively. AUX1: ToF, AUX2: DHT22
# You can use them for other DIY components as needed. Do not exceed 250ma of total current on these pins.

# While RATGDO path are included, the ESP32-C6 board does not support RATGDO features at this time.
# RATGDO needs to be refactored to work with the ESP-IDF framework at this time.
# For now only SecPlus GDO features are supported on the ESP32-C6 board.

packages:
  remote_package:
    url: https://github.com/gelidusresearch/grgdo
    files:
#      - path: packages/ratgdo-base.yaml                    # enable base RATGDO firmware                   - Not supported on ESP32-C6
#      - path: packages/ratgdo-secplusv1.yaml               # enable RATGDO Security+v1 support and outputs - Not supported on ESP32-C6
#      - path: packages/ratgdo-secplusv2.yaml               # enable RATGDO Security+v2 support and outputs - Not supported on ESP32-C6
#      - path: packages/ratgdo-drycontact.yaml              # enable RATGDO Dry Contact support and outputs - Not supported on ESP32-C6
#      - path: packages/secplusgdo-secplusv1.yaml           # configure SecPlus GDO Security+v1 outputs
      - path: packages/secplusgdo-secplusv2.yaml           # configure SecPlus GDO Security+v2 outputs
      - path: packages/secplusgdo-tof.yaml                 # enable ToF sensor
      - path: packages/grgdo-dht22.yaml                    # enable DHT22 sensor (any firmware)

    ref: main
    refresh: 1s

dashboard_import:
  package_import_url: github://gelidusresearch/grgdo/grgdov3-board-secplus-gdo-thread.yaml@main
  import_full_config: true


# Enable logging
logger:

# Enable Home Assistant API
api:
  #encryption:
    #key: !secret api_encryption_key

ota:
  - platform: esphome              # Works with Thread networks however ota updates will be slower than WiFi
    #password: !secret ota_password
  - platform: web_server           # Works with Thread networks


network:
  enable_ipv6: true

openthread:
  device_type: MTD
  tlv: !secret tlv
  force_dataset: True

safe_mode:                         # Highly recommended when making frequent changes

web_server:                        # Works with Thread networks and will be slow on initial load
  port: 80
  version: 3
#  username: !secret web_user      # enable for minimal security
#  password: !secret web_password  # needs secrets file entries created first
