external_components:
  - source: github://gelidusresearch/esphome-secplus-gdo
    components: [ secplus_gdo ]
    refresh: 0s

# external_components:
#  - source:
#      path: X:\github\descipher\secplus-gdo\components
#      type: local
#    components: [ secplus_gdo ]

substitutions:
  id_prefix: grgdo1
  friendly_name: "GRGDO1"
  uart_tx_pin: GPIO22           # J4 Pin 1 or 3 Red CTRL
  uart_rx_pin: GPIO21           # J4 Pin 1 or 3 Red CTRL
  tof_sda_pin: GPIO3
  tof_scl_pin: GPIO1
  input_obst_pin: GPIO23        # J4 Pin 4 Grey OBST - not required with secplus_gdo
  dry_contact_open_pin: GPIO17  # J4 Pin 6 Green
  dry_contact_close_pin: GPIO19 # J4 Pin 7 Blue
  dry_contact_light_pin: GPIO18 # J4 Pin 8 Orange
  garage_door_cover_name: Garage Door
  garage_light_name: Garage Light
  garage_openings_name: Garage Openings
  garage_lock_name: Lock
  garage_motion_name: Motion
  garage_obstruction_name: Obstruction
  garage_motor_name: Motor
  garage_button_name: Wall Button
  garage_sync_name: Synced

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  baud_rate: 115200 # Set to 0 for GRGDO1 v1.0 hardware with the VL53L1X sensor

# Enable Home Assistant API
api:
  # encryption:
  #   key: "buaeVHSocwiVSueG+ffy8s9PcIpQVhuo2zxfqK7JXXw="

ota:
  - platform: esphome
#  password: "6ed976ff29cfc774b5feb6c825d69f33"

esphome:
  name: grgdo1
  friendly_name: GRGDO1
  comment: "ESP32: Garage Door Opener"
  platformio_options:
    build_flags:
      - -Wl,--wrap=esp_panic_handler


wifi:
  power_save_mode: none
  on_connect:
    lambda: id(grgdo).start_gdo();
  ssid: None #!secret wifi_ssid
  password: "" #!secret wifi_password

  ap:
    ssid: "GRGDO1"
    password: ""
    ap_timeout: 15s

captive_portal:

improv_serial:

web_server:

status_led:
  pin: GPIO4

secplus_gdo:
  id: ${id_prefix}
  input_gdo_pin: ${uart_rx_pin}
  output_gdo_pin: ${uart_tx_pin}
  input_obst_pin: ${input_obst_pin}
  # tof_sda_pin: ${tof_sda_pin}
  # tof_scl_pin: ${tof_scl_pin}

light:
  - platform: secplus_gdo
    name: Garage Door Light
    secplus_gdo_id: ${id_prefix}
    id: gdo_light

cover:
  - platform: secplus_gdo
    name: Garage Door
    secplus_gdo_id: ${id_prefix}
    id: gdo_door

text_sensor:
  - platform: version
    name: ESPHome Version
    hide_timestamp: true

sensor:
  - platform: secplus_gdo
    secplus_gdo_id: ${id_prefix}
    id: gdo_openings
    type: openings
    name: "Garage Door Openings"
    unit_of_measurement: "openings"
    icon: mdi:open-in-app
  # - platform: dht
  #   model: DHT22
  #   pin: GPIO3
  #   temperature:
  #     name: "Temperature"
  #     accuracy_decimals: 1
  #   humidity:
  #     name: "Humidity"
  #     accuracy_decimals: 1
  #   update_interval: 60s

lock:
  - platform: secplus_gdo
    id: gdo_lock_remotes
    secplus_gdo_id: ${id_prefix}
    name: "Lock remotes"
