substitutions:
  device_name: grgdo
  device_comment: Garage Door Controller
  device_type: ESP32-S BLE 4MB/360KB Dual Core 240MHz
  id_prefix: grgdov2
  friendly_name: "GRGDOv2"
  uart_tx_pin: GPIO22           # J4 Pin 1 or 3 Red CTRL
  uart_rx_pin: GPIO21           # J4 Pin 1 or 3 Red CTRL
  input_obst_pin: GPIO23        # J4 Pin 4 Grey OBST - Hardware based obstruction input option
  dry_contact_open_pin: GPIO18  # J4 Pin 6 Green
  dry_contact_close_pin: GPIO19 # J4 Pin 7 Blue
  dry_contact_light_pin: GPIO17 # J4 Pin 8 Orange
  tof_sda_pin: GPIO26           # AUX1
  tof_scl_pin: GPIO25           # AUX1
  dht22_pin: GPIO27             # AUX2 or AUX1:GPIO26
  status_pin: GPIO4

esphome:
  name: ${device_name}
  friendly_name: ${disp_name}
  name_add_mac_suffix: true
  project:
    name: "Gelidus Research.Garage Door Controller"
    version: "1.0"

# With packages you can more easily tune your configuration by
# adding or removing variations as needed.
# Just uncomment the lines for the features you want to enable.
# This base configuration enables the correct pins for the ESP32S V2 board
# AUX1 (4Pin): GPIO26 and GPIO25, AUX2 (3Pin): GPIO27
# The ToF and DHT22 sensors are connected to the AUX1 and AUX2 ports respectively. AUX1: ToF, AUX2: DHT22
# You can use them for other DIY components as needed. Do not exceed 250ma of total current on these pins.

packages:
  remote_package_files:
    url: https://github.com/gelidusresearch/grgdo
    files:
#      - path: packages/grgdo-dht22.yaml                    # enable DHT22 sensor
#      - path: packages/grgdo-secplusgdo-tof.yaml           # enable ToF sensor
#      - path: packages/ratgdo-base.yaml                    # enable base RATGDO firmware
#      - path: packages/ratgdo-secplusv1.yaml               # enable RATGDO Security+v1 support and outputs
#      - path: packages/ratgdo-secplusv2.yaml               # enable RATGDO Security+v2 support and outputs
#      - path: packages/ratgdo-drycontact.yaml              # enable RATGDO Dry Contact support and outputs
      - path: packages/secplusgdo-base.yaml                # enable base SecPlus GDO functionality
#      - path: packages/secplusgdo-secplusv1.yaml           # configure SecPlus GDO Security+v1 outputs
#      - path: packages/secplusgdo-secplusv2.yaml           # configure SecPlus GDO Security+v2 outputs

    ref: main
    refresh: 1d

dashboard_import:
  package_import_url: github://gelidusresearch/grgdo@main
  import_full_config: false

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome              # Works with Thread networks however ota updates will be slow
  - platform: web_server           # Works with Thread networks

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ap_timeout: 20s

captive_portal:                    # Comment out with Thread networks

improv_serial:                     # Comment out with Thread networks

safe_mode:                         # Highly recommended when making frequent changes

web_server:                        # Works with Thread networks and will be slow on initial load
  port: 80
  version: 3
#  username: !secret web_user      # enable for minimal security
#  password: !secret web_password  # needs secrets file entries created first

status_led:
  pin: ${status_pin}
