# GDO setup guide ver 2025.03.23
# The VL53L1X ToF Sensor on RATGDO firmmare requires the GelidusResearch Repo
external_components:
  - source:
      type: git
      url: https://github.com/gelidusresearch/esphome-ratgdo.git
      ref: "1.3.1"
    components: [ ratgdo ]
    refresh: 0s

substitutions:
  id_prefix: gdo
  friendly_name: "GDO1"
  uart_tx_pin: GPIO22           # J4 Pin 1 Red or 3 Blue to Opener Red CTRL terminal
  uart_rx_pin: GPIO21           # J4 Pin 1 Red or 3 Blue to Opener Red CTRL terminal
  input_obst_pin: GPIO23        # J4 Pin 4 Grey OBST
  dry_contact_open_pin: GPIO18  # J4 Pin 6 Green
  dry_contact_close_pin: GPIO19 # J4 Pin 7 Blue
  dry_contact_light_pin: GPIO17 # J4 Pin 8 Orange
  dht22_pin: GPIO26                   # GPIO3 = v1 board, GPIO26 = AUX1 v2 board, GPIO27 = AUX2 v2 board
  tof_sda_pin: GPIO26           # GPIO26 = v2 board, GPIO3 = v1 board
  tof_scl_pin: GPIO25           # GPIO25 = v2 board, GPIO1 = v1 board
  status_led_pin: GPIO4         # GPIO4
  i2c_sda_pin: GPIO25
  i2c_scl_pin: GPIO26

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  project:
    name: Gelidus Research.Garage Door Controller
    version: "1.3.1"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  - platform: esphome
  - platform: web_server

wifi:
  ap:

captive_portal:

improv_serial:

web_server:

preferences:
  flash_write_interval: 120s

#i2c:
#  - id: bus_a          # Optional I2C bus for ToF sensor
#    frequency: 100kHz
#    scan: true
#    sda: ${tof_sda_pin}
#    scl: ${tof_scl_pin}
#  - id: bus_b           # Optional I2C bus for ENS/AHT/DHT22 sensors use bus_a for ToF sensor
#    frequency: 100kHz
#    scan: true
#    sda: ${i2c_sda_pin}
#    scl: ${i2c_scl_pin}

ratgdo:
  id: ${id_prefix}
  input_gdo_pin: ${uart_rx_pin}
  output_gdo_pin: ${uart_tx_pin}
  input_obst_pin: ${input_obst_pin}
  #tof_sda_pin: ${tof_sda_pin}  # uncomment with ToF Sensor
  #tof_scl_pin: ${tof_scl_pin}  # uncomment with ToF Sensor
  protocol: secplusv2           # one of secplusv2, secplusv1 or drycontact

sensor:
  - platform: ratgdo
    id: ${id_prefix}_openings
    type: openings
    entity_category: diagnostic
    ratgdo_id: ${id_prefix}
    name: "Openings"
    unit_of_measurement: "openings"
    icon: mdi:open-in-app
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: wifi_signal_db
    update_interval: 30s
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

# Optional Add-on ENS160/AHT20
#  - platform: aht10
#    address: 0x38
#    variant: AHT20
#    temperature:
#      id: id_temperature_sensor
#      name: "AHT20 Temperature"
#    humidity:
#      id: id_humidity_sensor
#      name: "AHT20 Humidity"
#    update_interval: 60s

# Optional Add-on ToF Sensor
#  - platform: ratgdo
#    id: ${id_prefix}_vehicle_distance_actual
#    type: distance
#    name: "Vehicle Distance Measured"
#    ratgdo_id: ${id_prefix}
#    unit_of_measurement: "mm"
#    internal: true
#    filters:
#      - throttle: 500ms
#      - heartbeat: 1s

#  - platform: copy
#    source_id: ${id_prefix}_vehicle_distance_actual
#    name: Vehicle Distance Measure Filtered
#    filters:
#      - min:
#          window_size: 6   # increase window if the reading varies to much
#          send_every: 1
#      - quantile           # remove outliers that are not in the 90th percentile
#          window_size: 12
#          send_every: 1
#          quantile: .9     # Useful for surfaces that scatter the signal and other issues

# Optional Add-on DHT22
#  - platform: dht
#    model: DHT22
#    pin: ${dht22_pin}
#    temperature:
#      name: "Temperature"
#      accuracy_decimals: 1
#      filters:                                  # °F vs default °C
#       - lambda: return x * (9.0/5.0) + 32.0;
#      unit_of_measurement: "°F"
#    humidity:
#      name: "Humidity"
#      accuracy_decimals: 1
#    update_interval: 60s

binary_sensor:
  - platform: ratgdo
    type: motion
    id: ${id_prefix}_motion
    ratgdo_id: ${id_prefix}
    name: "Motion"
    device_class: motion

  - platform: ratgdo
    type: obstruction
    id: ${id_prefix}_obstruction
    ratgdo_id: ${id_prefix}
    name: "Obstruction"
    device_class: problem

  - platform: ratgdo
    type: button
    id: ${id_prefix}_button
    ratgdo_id: ${id_prefix}
    name: "Button"
    entity_category: diagnostic

  - platform: ratgdo
    type: motor
    id: ${id_prefix}_motor
    ratgdo_id: ${id_prefix}
    name: "Motor"
    device_class: running
    entity_category: diagnostic

# Optional Add-on ToF Sensor
#  - platform: ratgdo
#    ratgdo_id: ${id_prefix}
#    id: ${id_prefix}_vehicle_detected
#    type: vehicle_detected
#    name: "Vehicle State Detected"

#  - platform: ratgdo
#    ratgdo_id: ${id_prefix}
#    id: ${id_prefix}_vehicle_arriving
#    type: vehicle_arriving
#    name: "Vehicle State Arriving"

#  - platform: ratgdo
#    ratgdo_id: ${id_prefix}
#    id: ${id_prefix}_vehicle_leaving
#    type: vehicle_leaving
#    name: "Vehicle State Leaving"

  - platform: gpio
    id: "${id_prefix}_dry_contact_open"
    pin:
      number: ${dry_contact_open_pin}  #  dry contact for opening door
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact open"
    entity_category: diagnostic
    on_press:
      - if:
          condition:
            binary_sensor.is_off: ${id_prefix}_dry_contact_close
          then:
            - cover.open: ${id_prefix}_garage_door
  - platform: gpio
    id: "${id_prefix}_dry_contact_close"
    pin:
      number: ${dry_contact_close_pin}  # dry contact for closing door
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact close"
    entity_category: diagnostic
    on_press:
      - if:
          condition:
            binary_sensor.is_off: ${id_prefix}_dry_contact_open
          then:
            - cover.close: ${id_prefix}_garage_door
  - platform: gpio
    id: "${id_prefix}_dry_contact_light"
    pin:
      number: ${dry_contact_light_pin}  # dry contact for triggering light
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact light"
    entity_category: diagnostic
    on_press:
      - light.toggle: ${id_prefix}_light

number:
  - platform: ratgdo
    id: ${id_prefix}_rolling_code_counter
    type: rolling_code_counter
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Rolling code counter"
    mode: box
    unit_of_measurement: "codes"

  - platform: ratgdo
    id: ${id_prefix}_opening_duration
    type: opening_duration
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Opening duration"
    unit_of_measurement: "s"

  - platform: ratgdo
    id: ${id_prefix}_closing_duration
    type: closing_duration
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Closing duration"
    unit_of_measurement: "s"

  - platform: ratgdo
    id: ${id_prefix}_client_id
    type: client_id
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Client ID"
    mode: box

# Optional TTC
  - platform: ratgdo
    id: ${id_prefix}_time_to_close
    type: time_to_close
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Time to close"
    mode: box
    unit_of_measurement: "s"

switch:
  - platform: ratgdo
    id: ${id_prefix}_close_notification
    type: close_notification
    ratgdo_id: ${id_prefix}
    name: "Close Notification"
    restore_mode: RESTORE_DEFAULT_OFF
    icon: "mdi:bell-alert"

  - platform: ratgdo
    id: ${id_prefix}_invert_obstruction
    type: invert_obstruction
    ratgdo_id: ${id_prefix}
    name: "Invert Obstruction"
    restore_mode: RESTORE_DEFAULT_OFF

# Optional Add-on ToF Sensor
#  - platform: ratgdo
#    id: ${id_prefix}_target_distance_measurement
#    type: target_distance_measurement
#    entity_category: config
#    ratgdo_id: ${id_prefix}
#    name: "Vehicle Distance Target"
#    mode: box
#    unit_of_measurement: "mm"

cover:
  - platform: ratgdo
    id: ${id_prefix}_garage_door
    device_class: garage
    name: "Door"
    ratgdo_id: ${id_prefix}

light:
  - platform: ratgdo
    id: ${id_prefix}_light
    name: "Light"
    ratgdo_id: ${id_prefix}

lock:
  - platform: ratgdo
    id: ${id_prefix}_lock_remotes
    name: "Lock remotes"
    ratgdo_id: ${id_prefix}

button:
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Safe mode boot"
    entity_category: diagnostic

  - platform: template
    id: ${id_prefix}_query_status
    entity_category: diagnostic
    name: "Query status"
    on_press:
      then:
        lambda: !lambda |-
          id(${id_prefix}).query_status();

  - platform: template
    id: ${id_prefix}_query_openings
    name: "Query openings"
    entity_category: diagnostic
    on_press:
      then:
        lambda: !lambda |-
          id(${id_prefix}).query_openings();

  - platform: template
    id: ${id_prefix}_sync
    name: "Sync"
    entity_category: diagnostic
    on_press:
      then:
        lambda: !lambda |-
          id(${id_prefix}).sync();

  - platform: template
    id: ${id_prefix}_toggle_door
    name: "Toggle door"
    on_press:
      then:
        lambda: !lambda |-
          id(${id_prefix}).door_toggle();

status_led:
  pin: ${status_led_pin}
