# GRGDO setup guide ver 2026.03.18
external_components:
  - source: github://GelidusResearch/esphome-secplus-gdo
    components: [ secplus_gdo ]
    refresh: 0s
# ToF Sensor
#  - source: github://GelidusResearch/ToF
#    components: [vl53l1x]
#    refresh: 0s

substitutions:
  id_prefix: grgdo
  friendly_name: "GRGDO"
  uart_tx_pin: GPIO22           # J4 Pin 1 or 3 Red CTRL
  uart_rx_pin: GPIO21           # J4 Pin 1 or 3 Red CTRL
  input_obst_pin: GPIO23        # J4 Pin 4 Grey OBST - Hardware based obstruction input option
  dry_contact_open_pin: GPIO18  # J4 Pin 6 Green
  dry_contact_close_pin: GPIO19 # J4 Pin 7 Blue
  dry_contact_light_pin: GPIO17 # J4 Pin 8 Orange
  dht22_pin: GPIO27             # V2 or older AUX2=GPIO27 AUX1=GPIO26 V1=GPIO3
  tof_sda_pin: GPIO26           # v1 board=GPIO3 v2(USB-C) board=GPIO26
  tof_scl_pin: GPIO25           # v1 board=GPIO1 v2(USB-C) board=GPIO25
  garage_door_cover_name: Garage Door
  garage_light_name: Garage Light
  garage_openings_name: Garage Openings
  garage_lock_name: Lock
  garage_motion_name: Motion
  garage_obstruction_name: Obstruction
  garage_motor_name: Motor
  garage_button_name: Wall Button
  garage_sync_name: Synced

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: Gelidus Research.GRGDO1 Garage Door Controller
    version: "2.5"
  comment: "ESP32: Garage Door Opener"
  on_boot:
    - priority: -100
      then:
        - lambda: id(${id_prefix}).start_gdo();

dashboard_import:
  package_import_url: github://gelidusresearch/grgdo/imports/secplus.gdo.ultra.yaml@main
  import_full_config: true


wifi:

  ap:

captive_portal:

logger:

api:
#  encryption:
#    key: "YOUR API KEY GOES HERE"

ota:
  - platform: esphome
  - platform: web_server

improv_serial:

web_server:
  version: 3
  local: true

status_led:
  pin: GPIO4

secplus_gdo:
  id: ${id_prefix}
  input_gdo_pin: ${uart_rx_pin}
  output_gdo_pin: ${uart_tx_pin}
#  tof_distance_sensor: gdo_tof_distance_filtered  #post esphome 2026.1.x - required for VL53L1X ToF
  tof_distance_sensor: gdo_tof_distance           # Required for HC-SR04 ultrasonic distance sensor

#  input_obst_pin: ${input_obst_pin} # Used to enable physical pin obstruction sensing otherwise uses secplus data
#  tof_sda_pin: ${tof_sda_pin}       # pre esphome 2026.2.0 enable for VL53L1X
#  tof_scl_pin: ${tof_scl_pin}       # pre esphome 2026.2.0 enable for VL53L1X


# required for a VL53L1X ToF post esphome 2026.2.0
#i2c:
#  id: bus_a
#  sda: ${tof_sda_pin}
#  scl: ${tof_scl_pin}
#  scan: true
#  frequency: 400kHz

light:
  - platform: secplus_gdo
    name: Garage Door Light
    secplus_gdo_id: ${id_prefix}
    id: gdo_light

cover:
  - platform: secplus_gdo
    name: Garage Door
    secplus_gdo_id: ${id_prefix}
    id: gdo_door

text_sensor:
  - platform: version
    name: ESPHome Version
    hide_timestamp: true

sensor:
  - platform: secplus_gdo
    secplus_gdo_id: ${id_prefix}
    id: gdo_openings
    type: openings
    name: "Garage Door Openings"
    unit_of_measurement: "openings"
    icon: mdi:open-in-app
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

# Required for the HC-SR04 ultrasonic distance sensor
  - platform: ultrasonic
    id: gdo_tof_distance
    trigger_pin: ${tof_sda_pin}
    echo_pin: ${tof_scl_pin}
    name: "Vehicle Distance"
    timeout: 3.5m
    update_interval: 1s
    filters:
      - lambda: return x * 100.0;
    unit_of_measurement: "cm"

# Optional VL53L1X ToF Sensor - Requires defining the tof_sda_pin and tof_scl_pin and commenting out the HC-SR04 sensor above
#  - platform: vl53l1x
#    id: gdo_tof_distance
#    name: "Vehicle Measured Distance"
#    i2c_id: bus_a
#    address: 0x29
#    long_range: true
#    timing_budget: 100ms
#    timeout: 250ms
#    update_interval: 1s
#    internal: true
#    filters:
#      - lambda: return x * 100.0;
#    unit_of_measurement: "cm"

# Vehicle ToF Sensor - Required for the VL53L1X
#  - platform: secplus_gdo
#    secplus_gdo_id: ${id_prefix}
#    id: gdo_tof_distance
#    type: tof_distance
#    name: "Vehicle Measured Distance"
#    unit_of_measurement: "cm"
#    internal: true
#    filters:
#      - heartbeat: 250ms
#      - throttle: 1s

# Vehicle ToF Sensor - Required for the VL53L1X
#   - platform: copy
#     source_id: gdo_tof_distance
#     name: Vehicle Distance Measure Filtered
#     filters:
#       - quantile:           # remove outliers that are not in the 90th percentile
#           window_size: 16
#           send_every: 1
#           quantile: 0.9
#       - heartbeat: 2s

# Optional Add-on DHT22
#  - platform: dht
#    model: DHT22
#    pin: ${dht22_pin} # v1 board=GPIO3, v2.x board=GPIO26 (AUX1 4 Pin) or GPIO27 (AUX2 3 Pin)
#    temperature:
#      name: "Temperature"
#      accuracy_decimals: 1
#      filters:                                  # °F vs default °C
#       - lambda: return x * (9.0/5.0) + 32.0;
#      unit_of_measurement: "°F"
#    humidity:
#      name: "Humidity"
#      accuracy_decimals: 1
#    update_interval: 60s

lock:
  - platform: secplus_gdo
    id: gdo_lock_remotes
    secplus_gdo_id: ${id_prefix}
    name: "Lock remotes"

binary_sensor:
  - platform: secplus_gdo
    name: "Garage Motion Sensor"
    id: gdo_motion
    secplus_gdo_id: ${id_prefix}
    device_class: motion
    type: motion
  - platform: secplus_gdo
    name: "Garage Door Obstruction Sensor"
    id: gdo_obst
    secplus_gdo_id: ${id_prefix}
    device_class: problem
    type: obstruction
  - platform: secplus_gdo
    name: "Garage Door Motor"
    id: gdo_motor
    secplus_gdo_id: ${id_prefix}
    device_class: running
    type: motor
  - platform: secplus_gdo
    name: "Garage Button"
    id: gdo_button
    secplus_gdo_id: ${id_prefix}
    entity_category: diagnostic
    type: button
  - platform: secplus_gdo
    name: $garage_sync_name
    id: gdo_synced
    secplus_gdo_id: ${id_prefix}
    type: sync
    device_class: connectivity
# Required for either the VL53L1X or the HC-SR04
  - platform: secplus_gdo
    secplus_gdo_id: ${id_prefix}
    id: gdo_vehicle_parked
    type: vehicle_parked
    name: "Vehicle parked"

  - platform: secplus_gdo
    secplus_gdo_id: ${id_prefix}
    id: gdo_vehicle_arriving
    type: vehicle_arriving
    name: "Vehicle arriving"

  - platform: secplus_gdo
    secplus_gdo_id: ${id_prefix}
    id: gdo_vehicle_leaving
    type: vehicle_leaving
    name: "Vehicle leaving"

  - platform: gpio
    id: "${id_prefix}_dry_contact_open"
    pin:
      number: ${dry_contact_open_pin}  #  dry contact for opening door
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact open"
    entity_category: diagnostic
    on_press:
      - if:
          condition:
            binary_sensor.is_off: ${id_prefix}_dry_contact_close
          then:
            - cover.open: gdo_door
  - platform: gpio
    id: "${id_prefix}_dry_contact_close"
    pin:
      number: ${dry_contact_close_pin}  # dry contact for closing door
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact close"
    entity_category: diagnostic
    on_press:
      - if:
          condition:
            binary_sensor.is_off: ${id_prefix}_dry_contact_open
          then:
            - cover.close: gdo_door
  - platform: gpio
    id: "${id_prefix}_dry_contact_light"
    pin:
      number: ${dry_contact_light_pin}  # dry contact for triggering light
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact light"
    entity_category: diagnostic
    on_press:
      then:
        - light.toggle: gdo_light
    disabled_by_default: false

switch:
  - platform: secplus_gdo
    id: gdo_learn
    type: learn
    secplus_gdo_id: ${id_prefix}
    name: Learn
    icon: mdi:plus-box
    entity_category: config

  - platform: secplus_gdo
    id: gdo_toggle_only
    type: toggle_only
    secplus_gdo_id: ${id_prefix}
    name: Toggle Only
    icon: mdi:plus-box

  - platform: secplus_gdo
    id: gdo_obst_override
    type: obst_override
    secplus_gdo_id: ${id_prefix}
    name: Obstruction Override
    icon: mdi:plus-box

select:
  - platform: secplus_gdo
    id: gdo_protocol
    secplus_gdo_id: ${id_prefix}
    name: protocol
    icon: mdi:settings
    entity_category: config

number:
  - platform: secplus_gdo
    name: Opening duration
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_open_duration
    type: open_duration
    unit_of_measurement: "ms"
    internal: true

  - platform: secplus_gdo
    name: Closing duration
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_close_duration
    type: close_duration
    unit_of_measurement: "ms"

  - platform: secplus_gdo
    name: Client ID
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_client_id
    type: client_id
    mode: box

  - platform: secplus_gdo
    name: Rolling Code
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_rolling_code
    type: rolling_code
    mode: box

  # Remidiates wall button brownouts by throttling TX activity
  # 350ms recommened on 880LM units
  - platform: secplus_gdo
    name: Min Command Interval
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_min_command_interval
    type: min_command_interval
    mode: box
    unit_of_measurement: "ms"

  # Add Time Till Close (TTC) control, 0s = disabled
  - platform: secplus_gdo
    name: Time Till Close
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_time_to_close
    type: time_to_close
    mode: box
    unit_of_measurement: "s"

# Required for either the VL53L1X or the HC-SR04
  - platform: secplus_gdo
    name: "Vehicle Parked Threshold"
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_vehicle_parked_threshold
    type: vehicle_parked_threshold
    mode: box
    unit_of_measurement: "cm"

  - platform: secplus_gdo
    name: "Vehicle Parked Threshold Variance"
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_vehicle_parked_threshold_variance
    type: vehicle_parked_threshold_variance
    mode: box

button:
  - platform: restart
    name: Restart
    id: restart_button
    entity_category: config
  - platform: factory_reset
    name: Factory Reset
    entity_category: config
  - platform: template
    name: Reset door timings
    entity_category: config
    on_press:
      - number.set:
          id: gdo_open_duration
          value: 0
      - number.set:
          id: gdo_close_duration
          value: 0
      - button.press:
          id: restart_button
  - platform: template
    name: Re-sync
    entity_category: config
    on_press:
      - number.increment:
          id: gdo_client_id
      - button.press:
          id: restart_button
